#!/bin/bash

KEYBINDINGS_FILE="$HOME/.config/hypr/modules/keybindings.lua"

# Parse keybindings and format for rofi
parse_keybindings() {
    echo "=== General ==="
    echo "SUPER + Q            → Terminal (kitty)"
    echo "SUPER + C            → Close window"
    echo "SUPER + M            → Logout/Shutdown"
    echo "SUPER + E            → File manager (dolphin)"
    echo "SUPER + T            → Toggle float"
    echo "SUPER + F            → Toggle fullscreen"
    echo "SUPER + A            → Application menu"
    echo "SUPER + W            → Window menu"
    echo "SUPER + P            → Pseudo tiling"
    echo "SUPER + Return       → Float terminal"
    echo ""
    echo "=== Focus ==="
    echo "SUPER + ←            → Focus left"
    echo "SUPER + →            → Focus right"
    echo "SUPER + ↑            → Focus up"
    echo "SUPER + ↓            → Focus down"
    echo ""
    echo "=== Scrolling Layout ==="
    echo "SUPER + SHIFT + H    → Swap column left"
    echo "SUPER + SHIFT + L    → Swap column right"
    echo "SUPER + ,            → Scroll viewport left"
    echo "SUPER + .            → Scroll viewport right"
    echo "SUPER + [            → Previous column width"
    echo "SUPER + ]            → Next column width"
    echo "SUPER + O            → Fit active column"
    echo "SUPER + SHIFT + O    → Fit all columns"
    echo "SUPER + G            → Promote window"
    echo "SUPER + SHIFT + G    → Consume/expel window"
    echo ""
    echo "=== Workspaces ==="
    echo "SUPER + 1-9          → Switch to workspace"
    echo "SUPER + SHIFT + 1-9  → Move window to workspace"
    echo "SUPER + S            → Toggle special workspace"
    echo "SUPER + SHIFT + S    → Move to special workspace"
    echo ""
    echo "=== Media Keys ==="
    echo "XF86AudioRaise       → Volume up"
    echo "XF86AudioLower       → Volume down"
    echo "XF86AudioMute        → Mute toggle"
    echo "XF86AudioMicMute     → Mic mute toggle"
    echo "XF86MonBrightnessUp  → Brightness up"
    echo "XF86MonBrightnessDown→ Brightness down"
    echo "XF86AudioNext        → Next track"
    echo "XF86AudioPause       → Play/Pause"
    echo "XF86AudioPlay        → Play/Pause"
    echo "XF86AudioPrev        → Previous track"
    echo ""
    echo "=== Waybar Music Controls ==="
    echo " 󰒮               → Previous track"
    echo " 󰏤/󰐊            → Play/Pause"
    echo " 󰒭               → Next track"
    echo ""
    echo "=== Screenshots ==="
    echo "SHIFT + Print        → Screenshot full screen"
    echo "Print                → Screenshot region"
    echo "CTRL + Print         → Screenshot window"
    echo ""
    echo "=== Utilities ==="
    echo "SUPER + V            → Rofi Clipboard"
    echo "SUPER + SHIFT + V    → Clipboard Manager"
    echo "SUPER + N            → Notification center (Tide)"
    echo "SUPER + SHIFT + B    → Reload waybar"
    echo "SUPER + K            → Show keybindings"
    echo ""
    echo "=== Kitty Terminal ==="
    echo "Ctrl+Shift+Enter    → New tab (current dir)"
    echo "Ctrl+Shift+X        → Horizontal split"
    echo "Ctrl+Shift+S        → Vertical split"
    echo "Ctrl+Shift+W        → New window"
    echo "Ctrl+Shift+L        → Next layout"
    echo "Ctrl+Shift+]        → Font size +2"
    echo "Ctrl+Shift+-        → Font size -2"
    echo ""
    echo "=== Tide Island ==="
    echo "SUPER + Tab          → Workspace overview"
    echo "SUPER + Right        → Swipe right"
    echo "SUPER + Left         → Custom page"
    echo "SUPER + Down         → Clock"
    echo "SUPER + SHIFT + M    → Music player"
    echo "SUPER + SHIFT + C    → Control center"
    echo "SUPER + SHIFT + W    → Wallpaper picker"
    echo "SUPER + SHIFT + F    → Toggle island"
    echo "SUPER + slash        → App launcher"
}

parse_keybindings | rofi -dmenu -p "Keybindings" -i -no-select -location 4 -width 50
