matches:
  - trigger: ";gtbsc"
    replace: "GTBINGLAXXX"
  - trigger: ";gmi"
    replace: "gmicrochains"
  - trigger: ";dustt"
    replace: "$DUST"
  - trigger: ";mog"
    replace: "MOG"
  - trigger: ";zk"
    replace: "$ZK"
  - trigger: ";zensc"
    replace: "ZEIBNGLAXXX"
  - trigger: ";zena"
    replace: "2265733004"
  - trigger: ";stesc"
    replace: "NAMENGLA"
  - trigger: ";xp"
    replace: "XP"
  - trigger: ";hopium"
    replace: "$HOPIUM"
  - trigger: ";linea"
    replace: "$LINEA"
  - trigger: ";megaeth"
    replace: "MegaETH"
  - trigger: ";rabby"
    replace: "Rabby"
  - trigger: ";VPN"
    replace: "VPN"
  - trigger: ";onchain"
    replace: "On-chain"
  - trigger: ";offchain"
    replace: "Off-chain"
  - trigger: ";cornn"
    replace: "$CORN"
  - trigger: ";arb"
    replace: "$ARB"
  - trigger: ";ibtc"
    replace: "IBTC"
  - trigger: ";sei"
    replace: "$SEI"
  - trigger: ";dym"
    replace: "$DYM"
  - trigger: ";alt"
    replace: "ALTS"
  - trigger: ";iqoo"
    replace: "IQOO"
  - trigger: ";mises"
    replace: "Mises"
  - trigger: ";mask"
    replace: "$MASK"
  - trigger: ";okx"
    replace: "OKX"
  - trigger: ";web3"
    replace: "Web3"
  - trigger: ";evm"
    replace: "EVM"
  - trigger: ";WTH"
    replace: "WTH"
  - trigger: ";WTF"
    replace: "WTF"
  - trigger: ";ath"
    replace: "ATH"
  - trigger: ";htx"
    replace: "HTX"
  - trigger: ";lte"
    replace: "LTE"
  - trigger: ";WiFi"
    replace: "Wi-Fi"
  - trigger: ";hhh"
    replace: "—"
  - trigger: ";t3f"
    replace: "@OwNyOhOoD @cryptonaij @babaegbesu"
  - trigger: ";uu"
    replace: "🌟 DAY $ Yapping about @union_build Until I get a Yap on @KaitoAI"
  - trigger: ";xn"
    replace: "O Y I N S S 🥽"
  - trigger: ";leaderboard"
    replace: "LeaderBoard 👑"
  - trigger: "api"
    replace: "API"
  - trigger: "tx"
    replace: "transaction"
  - trigger: "infofi"
    replace: "InfoFi"
  - trigger: "socialfi"
    replace: "SocialFi"
  - trigger: "rpc"
    replace: "RPC"
  - trigger: "$wbtc"
    replace: "$WBTC"
  - trigger: ";sochw"
    replace: "0xb7396dcac2e493702360a2fb4ce7fe79fde15e8b"
  - trigger: ";yy"
    replace: "✅"
  - trigger: ";nn"
    replace: "❌"
  - trigger: ";cbz"
    replace: "•\n\nProvide the Output in a Code Block."
  - trigger: ";ooz"
    replace: "...\n\nProvide the Output Only."
  - trigger: ";tfz"
    replace: "...\n\nProvide the Output in a Tabular Form."
  - trigger: ";sea"
    replace: "-filter:replies filter:blue_verified (@anoma) "
  - trigger: ";tb"
    replace: "since:2025-07-01 until:2025-07-02 from:"
  - trigger: ";defi"
    replace: "DeFi"
  - trigger: "tge"
    replace: "TGE"
  - trigger: ";in"
    replace: "$IN"
  - trigger: "zkgm"
    replace: "zkgm"
  - trigger: "Zkgm"
    replace: "zkgm"
  - trigger: "kaitoai"
    replace: "KaitoAi"
  - trigger: "Kaitoai"
    replace: "KaitoAi"
  - trigger: "alot"
    replace: "a lot"
  - trigger: "Alot"
    replace: "A lot"
  - trigger: ";ethos"
    replace: "https://app.ethos.network/profile/x/0yinss"
  - trigger: ":gcm"
    replace: "ALways use a commit message that best discribe the changes and make sure you always start the commit message with an emoji that best describes the canges made. i.e. bug emoji wen it's a bug fix along with the brief descriptions\n\ncheck each files for diff\ncommit each files \nthen push to repo"

  - trigger: "thats"
    replace: "that's"

  - trigger: ";pl"
    replace: "https://pisol.com.ng"
